[project]
name = "ai-papers-search-tool"
version = "0.1.0"
description = "Automatic paper clustering and search tool by fastext from Facebook Research"
authors = ["George Araujo <george.gcac@gmail.com>"]
license = "BSD-3"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "pyarrow>=23.0.1",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "tqdm>=4.67.3",
    "unidecode>=1.4.0",
]
